package io.vertx.codegen.protobuf.generator;

import io.vertx.codegen.DataObjectModel;
import io.vertx.codegen.EnumModel;
import io.vertx.codegen.EnumValueInfo;
import io.vertx.codegen.Generator;
import io.vertx.codegen.Model;
import io.vertx.codegen.PropertyInfo;
import io.vertx.codegen.annotations.DataObject;
import io.vertx.codegen.annotations.ModuleGen;
import io.vertx.codegen.protobuf.annotations.JsonProtoEncoding;
import io.vertx.codegen.type.ClassKind;

import java.io.PrintWriter;
import java.io.StringWriter;
import java.lang.annotation.Annotation;
import java.util.Arrays;
import java.util.Collection;
import java.util.HashSet;
import java.util.Map;

public class ProtoFileGen extends Generator<Model> {

  public ProtoFileGen() {
    name = "protobuf";
    kinds = new HashSet<>();
    kinds.add("dataObject");
    kinds.add("enum");
    incremental = true;
  }

  @Override
  public Collection<Class<? extends Annotation>> annotations() {
    return Arrays.asList(DataObject.class, ModuleGen.class);
  }

  @Override
  public String filename(Model model) {
    return "resources/dataobjects.proto";
  }

  @Override
  public String render(Model model, int index, int size, Map<String, Object> session) {
    if (model instanceof EnumModel) {
      return renderEnumModel((EnumModel) model, index);
    } else if (model instanceof DataObjectModel) {
      return renderDataObjectModel((DataObjectModel) model, index);
    } else {
      throw new RuntimeException("Unsupported model type " + model.getClass().getName());
    }
  }

  private String renderEnumModel(EnumModel model, int index) {
    StringWriter buffer = new StringWriter();
    PrintWriter writer = new PrintWriter(buffer);
    int enumIntValue = 0; // auto-increment for now
    writer.print("enum " + model.getElement().getSimpleName() + " {\n");
    for (EnumValueInfo enumValueInfo: model.getValues()) {
      writer.print("  " + enumValueInfo.getIdentifier() + " = " + enumIntValue + ";\n");
      enumIntValue++;
    }
    writer.print("}\n");
    writer.print("\n");
    return buffer.toString();
  }

  private String renderDataObjectModel(DataObjectModel model, int index) {
    StringWriter buffer = new StringWriter();
    PrintWriter writer = new PrintWriter(buffer);

    JsonProtoEncoding jsonProtoEncoding = JsonProtoEncodingSelector.select(model);

    if (index == 0) {
      writer.print("// Automatically generated by vertx-codegen.\n");
      writer.print("// Do not edit. Changes made to this file may be overwritten.\n");
      writer.print("\n");
      writer.print("syntax = \"proto3\";\n");
      writer.print("option java_multiple_files = true;\n");
      writer.print("option java_package = \"io.vertx.protobuf.generated\";\n");
      writer.print("\n");
      writer.print("package io.vertx.protobuf.generated;\n");
      writer.print("\n");
      if (jsonProtoEncoding == JsonProtoEncoding.GOOGLE_STRUCT) {
        writer.print("import \"struct.proto\";\n");
      } else {
        writer.print("import \"vertx-struct.proto\";\n");
      }
      writer.print("import \"datetime.proto\";\n");
      writer.print("\n");
    }

    String messageName = model.getType().getSimpleName();
    int fieldNumber = 1;

    writer.print("message " + messageName + " {\n");
    for (PropertyInfo prop : model.getPropertyMap().values()) {
      ClassKind propKind = prop.getType().getKind();
      ProtoProperty protoProperty = ProtoProperty.getProtoProperty(prop, fieldNumber);

      String protoType;
      if (propKind.basic) {
        protoType = protoProperty.getProtoType().value;
      } else {
        if (protoProperty.isBuiltinType()) {
          protoType = "io.vertx.protobuf." + protoProperty.getBuiltInType();
        } else {
          protoType = protoProperty.getMessage();
        }
      }

      if (prop.getKind().isList()) {
        writer.print("  repeated " + protoType + " " + prop.getName() + " = " + fieldNumber + ";\n");
      } else if (prop.getKind().isMap()) {
        writer.print("  map<string, " + protoType + "> " + prop.getName() + " = " + fieldNumber + ";\n");
      } else {
        writer.print("  " + protoType + " " + prop.getName() + " = " + fieldNumber + ";\n");
      }
      fieldNumber++;
    }
    writer.print("}\n");
    writer.print("\n");

    return buffer.toString();
  }
}
