/*
 * Copyright (c) 2011-2017 Contributors to the Eclipse Foundation
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License 2.0 which is available at
 * http://www.eclipse.org/legal/epl-2.0, or the Apache License, Version 2.0
 * which is available at https://www.apache.org/licenses/LICENSE-2.0.
 *
 * SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
 */

package io.vertx.test.codegen.converter;

import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.JsonArray;
import io.vertx.core.json.JsonObject;
import org.junit.Assert;
import org.junit.Test;

import static org.junit.Assert.*;

import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.time.ZonedDateTime;
import java.util.*;
import java.util.UUID;
import java.util.concurrent.TimeUnit;

/**
 * @author <a href="mailto:julien@julienviet.com">Julien Viet</a>
 */
public class DataObjectTest {

  private static final Base64.Decoder BASE64_DECODER = Base64.getUrlDecoder();
  private static final Base64.Encoder BASE64_ENCODER = Base64.getUrlEncoder().withoutPadding();

  private static JsonObject toJson(Map<String, Object> map) {
    JsonObject json = new JsonObject();
    map.forEach(json::put);
    return json;
  }

  @Test
  public void testJsonToDataObject() throws Exception {

    String key = TestUtils.randomAlphaString(10);
    String stringValue = TestUtils.randomAlphaString(20);
    boolean booleanValue = TestUtils.randomBoolean();
    byte byteValue = TestUtils.randomByte();
    short shortValue = TestUtils.randomShort();
    int intValue = TestUtils.randomInt();
    long longValue = TestUtils.randomLong();
    float floatValue = TestUtils.randomFloat();
    double doubleValue = TestUtils.randomDouble();
    char charValue = TestUtils.randomChar();
    Boolean boxedBooleanValue = TestUtils.randomBoolean();
    Byte boxedByteValue = TestUtils.randomByte();
    Short boxedShortValue = TestUtils.randomShort();
    Integer boxedIntValue = TestUtils.randomInt();
    Long boxedLongValue = TestUtils.randomLong();
    Float boxedFloatValue = TestUtils.randomFloat();
    Double boxedDoubleValue = TestUtils.randomDouble();
    Character boxedCharValue = TestUtils.randomChar();
    NestedJsonObjectDataObject jsonObjectDataObject = new NestedJsonObjectDataObject().setValue(TestUtils.randomAlphaString(20));
    NestedStringDataObject stringDataObjectValue = new NestedStringDataObject().setValue(TestUtils.randomAlphaString(20));
    Buffer bufferValue = TestUtils.randomBuffer(20);
    JsonObject jsonObjectValue = new JsonObject().put("wibble", TestUtils.randomAlphaString(20));
    JsonArray jsonArrayValue = new JsonArray().add(TestUtils.randomAlphaString(20));
    TimeUnit enumValue = TimeUnit.values()[TestUtils.randomPositiveInt() % TimeUnit.values().length];
    ZonedDateTime methodMappedValue = ZonedDateTime.now();
    Duration durationValue = Duration.ofSeconds(methodMappedValue.toEpochSecond());
    Object objectValue = stringValue;
    TestCustomEnum customEnumValue = TestCustomEnum.DEV;
    AutoMapped autoMappedValue = AutoMapped.of("vertx.io", 80);
    AutoMappedWithVertxGen autoMappedWithVertxGenValue = AutoMappedWithVertxGen.of("vertx.io", 80);
    UUID uuidValue = UUID.randomUUID();

    Map<String, Object> map = new HashMap<>();
    map.put(TestUtils.randomAlphaString(10), TestUtils.randomAlphaString(20));
    map.put(TestUtils.randomAlphaString(10), TestUtils.randomBoolean());
    map.put(TestUtils.randomAlphaString(10), TestUtils.randomInt());
    List<Object> list = new ArrayList<>();
    list.add(TestUtils.randomAlphaString(20));
    list.add(TestUtils.randomBoolean());
    list.add(TestUtils.randomInt());

    JsonObject json = new JsonObject();
    json.put("stringValue", stringValue);
    json.put("primitiveBooleanValue", booleanValue);
    json.put("primitiveByteValue", byteValue);
    json.put("primitiveShortValue", shortValue);
    json.put("primitiveIntValue", intValue);
    json.put("primitiveLongValue", longValue);
    json.put("primitiveFloatValue", floatValue);
    json.put("primitiveDoubleValue", doubleValue);
    json.put("primitiveCharValue", Character.toString(charValue));
    json.put("boxedBooleanValue", boxedBooleanValue);
    json.put("boxedByteValue", boxedByteValue);
    json.put("boxedShortValue", boxedShortValue);
    json.put("boxedIntValue", boxedIntValue);
    json.put("boxedLongValue", boxedLongValue);
    json.put("boxedFloatValue", boxedFloatValue);
    json.put("boxedDoubleValue", boxedDoubleValue);
    json.put("boxedCharValue", Character.toString(boxedCharValue));
    json.put("jsonObjectDataObjectValue", jsonObjectDataObject.toJson());
    json.put("stringDataObjectValue", stringDataObjectValue.toJson());
    json.put("bufferValue", toBase64(bufferValue));
    json.put("jsonObjectValue", jsonObjectValue);
    json.put("jsonArrayValue", jsonArrayValue);
    json.put("enumValue", enumValue.toString());
    json.put("methodMappedValue", methodMappedValue.toString());
    json.put("durationValue", durationValue.toMillis());
    json.put("objectValue", objectValue.toString());
    json.put("noConverterDataObjectValue", new JsonObject());
    json.put("noConverter2DataObjectValue", new JsonObject());
    json.put("customEnumValue", customEnumValue.getShortName());
    json.put("autoMappedValue", autoMappedValue.toJson());
    json.put("autoMappedWithVertxGenValue", autoMappedWithVertxGenValue.toJson());
    json.put("uuidValue", uuidValue.toString());
    json.put("stringValueList", new JsonArray().add(stringValue));
    json.put("boxedBooleanValueList", new JsonArray().add(boxedBooleanValue));
    json.put("boxedByteValueList", new JsonArray().add(boxedByteValue));
    json.put("boxedShortValueList", new JsonArray().add(boxedShortValue));
    json.put("boxedIntValueList", new JsonArray().add(boxedIntValue));
    json.put("boxedLongValueList", new JsonArray().add(boxedLongValue));
    json.put("boxedFloatValueList", new JsonArray().add(boxedFloatValue));
    json.put("boxedDoubleValueList", new JsonArray().add(boxedDoubleValue));
    json.put("boxedCharValueList", new JsonArray().add(Character.toString(boxedCharValue)));
    json.put("jsonObjectDataObjectValueList", new JsonArray().add(jsonObjectDataObject.toJson()));
    json.put("stringDataObjectValueList", new JsonArray().add(stringDataObjectValue.toJson()));
    json.put("bufferValueList", new JsonArray().add(toBase64(bufferValue)));
    json.put("jsonObjectValueList", new JsonArray().add(jsonObjectValue));
    json.put("jsonArrayValueList", new JsonArray().add(jsonArrayValue));
    json.put("enumValueList", new JsonArray().add(enumValue.toString()));
    json.put("methodMappedValueList", new JsonArray().add(methodMappedValue.toString()));
    json.put("durationValueList", new JsonArray().add(durationValue.toMillis()));
    json.put("noConverterDataObjectValueList", new JsonArray().add(new JsonObject()));
    json.put("noConverter2DataObjectValueList", new JsonArray().add(new JsonObject()));
    json.put("objectValueList", new JsonArray().add(list.get(0)).add(list.get(1)).add(list.get(2)));
    json.put("customEnumValueList", new JsonArray().add(customEnumValue.getShortName()));
    json.put("autoMappedValueList", new JsonArray().add(autoMappedValue.toJson()));
    json.put("autoMappedWithVertxGenValueList", new JsonArray().add(autoMappedWithVertxGenValue.toJson()));
    json.put("stringValueSet", new JsonArray().add(stringValue));
    json.put("boxedBooleanValueSet", new JsonArray().add(boxedBooleanValue));
    json.put("boxedByteValueSet", new JsonArray().add(boxedByteValue));
    json.put("boxedShortValueSet", new JsonArray().add(boxedShortValue));
    json.put("boxedIntValueSet", new JsonArray().add(boxedIntValue));
    json.put("boxedLongValueSet", new JsonArray().add(boxedLongValue));
    json.put("boxedFloatValueSet", new JsonArray().add(boxedFloatValue));
    json.put("boxedDoubleValueSet", new JsonArray().add(boxedDoubleValue));
    json.put("boxedCharValueSet", new JsonArray().add(Character.toString(boxedCharValue)));
    json.put("jsonObjectDataObjectValueSet", new JsonArray().add(jsonObjectDataObject.toJson()));
    json.put("stringDataObjectValueSet", new JsonArray().add(stringDataObjectValue.toJson()));
    json.put("bufferValueSet", new JsonArray().add(toBase64(bufferValue)));
    json.put("jsonObjectValueSet", new JsonArray().add(jsonObjectValue));
    json.put("jsonArrayValueSet", new JsonArray().add(jsonArrayValue));
    json.put("enumValueSet", new JsonArray().add(enumValue.toString()));
    json.put("methodMappedValueSet", new JsonArray().add(methodMappedValue.toString()));
    json.put("durationValueSet", new JsonArray().add(durationValue.toMillis()));
    json.put("objectValueSet", new JsonArray().add(list.get(0)).add(list.get(1)).add(list.get(2)));
    json.put("noConverterDataObjectValueSet", new JsonArray().add(new JsonObject()));
    json.put("noConverter2DataObjectValueSet", new JsonArray().add(new JsonObject()));
    json.put("customEnumValueSet", new JsonArray().add(customEnumValue.getShortName()));
    json.put("autoMappedValueSet", new JsonArray().add(autoMappedValue.toJson()));
    json.put("autoMappedWithVertxGenValueSet", new JsonArray().add(autoMappedWithVertxGenValue.toJson()));
    json.put("addedStringValues", new JsonArray().add(stringValue));
    json.put("addedBooleanValues", new JsonArray().add(boxedBooleanValue));
    json.put("addedByteValues", new JsonArray().add(boxedByteValue));
    json.put("addedShortValues", new JsonArray().add(boxedShortValue));
    json.put("addedIntValues", new JsonArray().add(boxedIntValue));
    json.put("addedLongValues", new JsonArray().add(boxedLongValue));
    json.put("addedFloatValues", new JsonArray().add(boxedFloatValue));
    json.put("addedDoubleValues", new JsonArray().add(boxedDoubleValue));
    json.put("addedCharValues", new JsonArray().add(Character.toString(boxedCharValue)));
    json.put("addedBoxedBooleanValues", new JsonArray().add(boxedBooleanValue));
    json.put("addedBoxedByteValues", new JsonArray().add(boxedByteValue));
    json.put("addedBoxedShortValues", new JsonArray().add(boxedShortValue));
    json.put("addedBoxedIntValues", new JsonArray().add(boxedIntValue));
    json.put("addedBoxedLongValues", new JsonArray().add(boxedLongValue));
    json.put("addedBoxedFloatValues", new JsonArray().add(boxedFloatValue));
    json.put("addedBoxedDoubleValues", new JsonArray().add(boxedDoubleValue));
    json.put("addedBoxedCharValues", new JsonArray().add(Character.toString(boxedCharValue)));
    json.put("addedJsonObjectDataObjectValues", new JsonArray().add(jsonObjectDataObject.toJson()));
    json.put("addedStringDataObjectValues", new JsonArray().add(stringDataObjectValue.toJson()));
    json.put("addedBufferValues", new JsonArray().add(toBase64(bufferValue)));
    json.put("addedJsonObjectValues", new JsonArray().add(jsonObjectValue));
    json.put("addedJsonArrayValues", new JsonArray().add(jsonArrayValue));
    json.put("addedEnumValues", new JsonArray().add(enumValue.toString()));
    json.put("addedMethodMappedValues", new JsonArray().add(methodMappedValue.toString()));
    json.put("addedDurationValues", new JsonArray().add(durationValue.toMillis()));
    json.put("addedObjectValues", new JsonArray().add(list.get(0)).add(list.get(1)).add(list.get(2)));
    json.put("addedNoConverterDataObjectValues", new JsonArray().add(new JsonObject()));
    json.put("addedNoConverter2DataObjectValues", new JsonArray().add(new JsonObject()));
    json.put("addedCustomEnumValues", new JsonArray().add(customEnumValue.getShortName()));
    json.put("addedAutoMappedValues", new JsonArray().add(autoMappedValue.toJson()));
    json.put("addedAutoMappedWithVertxGenValues", new JsonArray().add(autoMappedWithVertxGenValue.toJson()));
    json.put("stringValueMap", new JsonObject().put(key, stringValue));
    json.put("boxedBooleanValueMap", new JsonObject().put(key, boxedBooleanValue));
    json.put("boxedByteValueMap", new JsonObject().put(key, boxedByteValue));
    json.put("boxedShortValueMap", new JsonObject().put(key, boxedShortValue));
    json.put("boxedIntValueMap", new JsonObject().put(key, boxedIntValue));
    json.put("boxedLongValueMap", new JsonObject().put(key, boxedLongValue));
    json.put("boxedFloatValueMap", new JsonObject().put(key, boxedFloatValue));
    json.put("boxedDoubleValueMap", new JsonObject().put(key, boxedDoubleValue));
    json.put("boxedCharValueMap", new JsonObject().put(key, Character.toString(boxedCharValue)));
    json.put("jsonObjectDataObjectValueMap", new JsonObject().put(key, jsonObjectDataObject.toJson()));
    json.put("stringDataObjectValueMap", new JsonObject().put(key, stringDataObjectValue.toJson()));
    json.put("bufferValueMap", new JsonObject().put(key, toBase64(bufferValue)));
    json.put("jsonObjectValueMap", new JsonObject().put(key, jsonObjectValue));
    json.put("jsonArrayValueMap", new JsonObject().put(key, jsonArrayValue));
    json.put("enumValueMap", new JsonObject().put(key, enumValue.toString()));
    json.put("methodMappedValueMap", new JsonObject().put(key, methodMappedValue.toString()));
    json.put("durationValueMap", new JsonObject().put(key, durationValue.toMillis()));
    json.put("objectValueMap", toJson(map));
    json.put("noConverterDataObjectValueMap", new JsonObject().put(key, new JsonObject()));
    json.put("noConverter2DataObjectValueMap", new JsonObject().put(key, new JsonObject()));
    json.put("customEnumValueMap", new JsonObject().put(key, customEnumValue.getShortName()));
    json.put("autoMappedValueMap", new JsonObject().put(key, autoMappedValue.toJson()));
    json.put("autoMappedWithVertxGenValueMap", new JsonObject().put(key, autoMappedValue.toJson()));
    json.put("keyedStringValues", new JsonObject().put(key, stringValue));
    json.put("keyedBoxedBooleanValues", new JsonObject().put(key, boxedBooleanValue));
    json.put("keyedBoxedByteValues", new JsonObject().put(key, boxedByteValue));
    json.put("keyedBoxedShortValues", new JsonObject().put(key, boxedShortValue));
    json.put("keyedBoxedIntValues", new JsonObject().put(key, boxedIntValue));
    json.put("keyedBoxedLongValues", new JsonObject().put(key, boxedLongValue));
    json.put("keyedBoxedFloatValues", new JsonObject().put(key, boxedFloatValue));
    json.put("keyedBoxedDoubleValues", new JsonObject().put(key, boxedDoubleValue));
    json.put("keyedBoxedCharValues", new JsonObject().put(key, Character.toString(boxedCharValue)));
    json.put("keyedJsonObjectDataObjectValues", new JsonObject().put(key, jsonObjectDataObject.toJson()));
    json.put("keyedStringDataObjectValues", new JsonObject().put(key, stringDataObjectValue.toJson()));
    json.put("keyedBufferValues", new JsonObject().put(key, toBase64(bufferValue)));
    json.put("keyedJsonObjectValues", new JsonObject().put(key, jsonObjectValue));
    json.put("keyedJsonArrayValues", new JsonObject().put(key, jsonArrayValue));
    json.put("keyedEnumValues", new JsonObject().put(key, enumValue.name()));
    json.put("keyedMethodMappedValues", new JsonObject().put(key, methodMappedValue.toString()));
    json.put("keyedDurationValues", new JsonObject().put(key, durationValue.toMillis()));
    json.put("keyedObjectValues", toJson(map));
    json.put("keyedNoConverterDataObjectValues", new JsonObject());
    json.put("keyedNoConverter2DataObjectValues", new JsonObject());
    json.put("keyedCustomEnumValues", new JsonObject().put(key, customEnumValue.getShortName()));
    json.put("keyedAutoMappedValues", new JsonObject().put(key, autoMappedValue.toJson()));
    json.put("keyedAutoMappedWithVertxGenValues", new JsonObject().put(key, autoMappedValue.toJson()));

    TestDataObject obj = new TestDataObject();
    TestDataObjectConverter.fromJson(json, obj);

    Assert.assertEquals(stringValue, obj.getStringValue());
    Assert.assertEquals(booleanValue, obj.isPrimitiveBooleanValue());
    Assert.assertEquals(byteValue, obj.getPrimitiveByteValue());
    Assert.assertEquals(shortValue, obj.getPrimitiveShortValue());
    Assert.assertEquals(intValue, obj.getPrimitiveIntValue());
    Assert.assertEquals(longValue, obj.getPrimitiveLongValue());
    Assert.assertEquals(floatValue, obj.getPrimitiveFloatValue(), 0);
    Assert.assertEquals(doubleValue, obj.getPrimitiveDoubleValue(), 0);
    Assert.assertEquals(charValue, obj.getPrimitiveCharValue());
    Assert.assertEquals(boxedBooleanValue, obj.isBoxedBooleanValue());
    Assert.assertEquals(boxedByteValue, obj.getBoxedByteValue());
    Assert.assertEquals(boxedShortValue, obj.getBoxedShortValue());
    Assert.assertEquals(boxedIntValue, obj.getBoxedIntValue());
    Assert.assertEquals(boxedLongValue, obj.getBoxedLongValue());
    Assert.assertEquals(boxedFloatValue, obj.getBoxedFloatValue(), 0);
    Assert.assertEquals(boxedDoubleValue, obj.getBoxedDoubleValue(), 0);
    Assert.assertEquals(boxedCharValue, obj.getBoxedCharValue());
    assertEquals(jsonObjectDataObject, obj.getJsonObjectDataObjectValue());
    assertEquals(stringDataObjectValue, obj.getStringDataObjectValue());
    Assert.assertEquals(bufferValue, obj.getBufferValue());
    Assert.assertEquals(jsonObjectValue, obj.getJsonObjectValue());
    Assert.assertEquals(jsonArrayValue, obj.getJsonArrayValue());
    Assert.assertEquals(enumValue, obj.getEnumValue());
    Assert.assertEquals(methodMappedValue, obj.getMethodMappedValue());
    Assert.assertEquals(durationValue, obj.getDurationValue());
    Assert.assertEquals(uuidValue, obj.getUuidValue());
    Assert.assertEquals(objectValue, obj.getObjectValue());
    Assert.assertNotNull(obj.getNoConverterDataObjectValue());
    Assert.assertNull(obj.getNoConverter2DataObjectValue());
    Assert.assertEquals(customEnumValue, obj.getCustomEnumValue());
    Assert.assertEquals(autoMappedValue.toJson(), obj.getAutoMappedValue().toJson());
    Assert.assertEquals(autoMappedWithVertxGenValue.toJson(), obj.getAutoMappedWithVertxGenValue().toJson());
    Assert.assertEquals(Collections.singletonList(stringValue), obj.getStringValueList());
    Assert.assertEquals(Collections.singletonList(boxedBooleanValue), obj.getBoxedBooleanValueList());
    Assert.assertEquals(Collections.singletonList(boxedByteValue), obj.getBoxedByteValueList());
    Assert.assertEquals(Collections.singletonList(boxedShortValue), obj.getBoxedShortValueList());
    Assert.assertEquals(Collections.singletonList(boxedIntValue), obj.getBoxedIntValueList());
    Assert.assertEquals(Collections.singletonList(boxedLongValue), obj.getBoxedLongValueList());
    Assert.assertEquals(Collections.singletonList(boxedFloatValue), obj.getBoxedFloatValueList());
    Assert.assertEquals(Collections.singletonList(boxedDoubleValue), obj.getBoxedDoubleValueList());
    Assert.assertEquals(Collections.singletonList(boxedCharValue), obj.getBoxedCharValueList());
    Assert.assertEquals(Collections.singletonList(jsonObjectDataObject), obj.getJsonObjectDataObjectValueList());
    Assert.assertEquals(Collections.singletonList(stringDataObjectValue), obj.getStringDataObjectValueList());
    Assert.assertEquals(Collections.singletonList(bufferValue), obj.getBufferValueList());
    Assert.assertEquals(Collections.singletonList(jsonObjectValue), obj.getJsonObjectValueList());
    Assert.assertEquals(Collections.singletonList(jsonArrayValue), obj.getJsonArrayValueList());
    Assert.assertEquals(Collections.singletonList(enumValue), obj.getEnumValueList());
    Assert.assertEquals(Collections.singletonList(methodMappedValue), obj.getMethodMappedValueList());
    Assert.assertEquals(Collections.singletonList(durationValue), obj.getDurationValueList());
    Assert.assertEquals(list, obj.getObjectValueList());
    Assert.assertEquals(1, obj.getNoConverterDataObjectValueList().size());
    Assert.assertNull(obj.getNoConverter2DataObjectValueList());
    Assert.assertEquals(Collections.singletonList(customEnumValue), obj.getCustomEnumValueList());
    Assert.assertEquals(Collections.singletonList(autoMappedValue), obj.getAutoMappedValueList());
    Assert.assertEquals(Collections.singletonList(autoMappedWithVertxGenValue), obj.getAutoMappedWithVertxGenValueList());
    Assert.assertEquals(Collections.singleton(stringValue), obj.getStringValueSet());
    Assert.assertEquals(Collections.singleton(boxedBooleanValue), obj.getBoxedBooleanValueSet());
    Assert.assertEquals(Collections.singleton(boxedByteValue), obj.getBoxedByteValueSet());
    Assert.assertEquals(Collections.singleton(boxedShortValue), obj.getBoxedShortValueSet());
    Assert.assertEquals(Collections.singleton(boxedIntValue), obj.getBoxedIntValueSet());
    Assert.assertEquals(Collections.singleton(boxedLongValue), obj.getBoxedLongValueSet());
    Assert.assertEquals(Collections.singleton(boxedFloatValue), obj.getBoxedFloatValueSet());
    Assert.assertEquals(Collections.singleton(boxedDoubleValue), obj.getBoxedDoubleValueSet());
    Assert.assertEquals(Collections.singleton(boxedCharValue), obj.getBoxedCharValueSet());
    Assert.assertEquals(Collections.singleton(jsonObjectDataObject), obj.getJsonObjectDataObjectValueSet());
    Assert.assertEquals(Collections.singleton(stringDataObjectValue), obj.getStringDataObjectValueSet());
    Assert.assertEquals(Collections.singleton(bufferValue), obj.getBufferValueSet());
    Assert.assertEquals(Collections.singleton(jsonObjectValue), obj.getJsonObjectValueSet());
    Assert.assertEquals(Collections.singleton(jsonArrayValue), obj.getJsonArrayValueSet());
    Assert.assertEquals(Collections.singleton(enumValue), obj.getEnumValueSet());
    Assert.assertEquals(Collections.singleton(methodMappedValue), obj.getMethodMappedValueSet());
    Assert.assertEquals(Collections.singleton(durationValue), obj.getDurationValueSet());
    Assert.assertEquals(new LinkedHashSet<>(list), obj.getObjectValueSet());
    Assert.assertEquals(1, obj.getNoConverterDataObjectValueSet().size());
    Assert.assertNull(obj.getNoConverter2DataObjectValueSet());
    Assert.assertEquals(Collections.singleton(customEnumValue), obj.getCustomEnumValueSet());
    Assert.assertEquals(Collections.singleton(autoMappedValue), obj.getAutoMappedValueSet());
    Assert.assertEquals(Collections.singleton(autoMappedWithVertxGenValue), obj.getAutoMappedWithVertxGenValueSet());
    Assert.assertEquals(Collections.singletonList(stringValue), obj.getAddedStringValues());
    Assert.assertEquals(Collections.singletonList(boxedBooleanValue), obj.getAddedBoxedBooleanValues());
    Assert.assertEquals(Collections.singletonList(boxedByteValue), obj.getAddedBoxedByteValues());
    Assert.assertEquals(Collections.singletonList(boxedShortValue), obj.getAddedBoxedShortValues());
    Assert.assertEquals(Collections.singletonList(boxedIntValue), obj.getAddedBoxedIntValues());
    Assert.assertEquals(Collections.singletonList(boxedLongValue), obj.getAddedBoxedLongValues());
    Assert.assertEquals(Collections.singletonList(boxedFloatValue), obj.getAddedBoxedFloatValues());
    Assert.assertEquals(Collections.singletonList(boxedDoubleValue), obj.getAddedBoxedDoubleValues());
    Assert.assertEquals(Collections.singletonList(boxedCharValue), obj.getAddedBoxedCharValues());
    Assert.assertEquals(Collections.singletonList(jsonObjectDataObject), obj.getAddedJsonObjectDataObjectValues());
    Assert.assertEquals(Collections.singletonList(stringDataObjectValue), obj.getAddedStringDataObjectValues());
    Assert.assertEquals(Collections.singletonList(bufferValue), obj.getAddedBufferValues());
    Assert.assertEquals(Collections.singletonList(jsonObjectValue), obj.getAddedJsonObjectValues());
    Assert.assertEquals(Collections.singletonList(jsonArrayValue), obj.getAddedJsonArrayValues());
    Assert.assertEquals(Collections.singletonList(enumValue), obj.getAddedEnumValues());
    Assert.assertEquals(Collections.singletonList(methodMappedValue), obj.getAddedMethodMappedValues());
    Assert.assertEquals(Collections.singletonList(durationValue), obj.getAddedDurationValues());
    Assert.assertEquals(list, obj.getAddedObjectValues());
    Assert.assertEquals(1, obj.getAddedNoConverterDataObjectValues().size());
    Assert.assertEquals(0, obj.getAddedNoConverter2DataObjectValues().size());
    Assert.assertEquals(Collections.singletonList(customEnumValue), obj.getAddedCustomEnumValues());
    Assert.assertEquals(Collections.singletonList(autoMappedValue), obj.getAddedAutoMappedValues());
    Assert.assertEquals(Collections.singletonList(autoMappedWithVertxGenValue), obj.getAddedAutoMappedWithVertxGenValues());
    Assert.assertEquals(Collections.singletonMap(key, stringValue), obj.getStringValueMap());
    Assert.assertEquals(Collections.singletonMap(key, boxedBooleanValue), obj.getBoxedBooleanValueMap());
    Assert.assertEquals(Collections.singletonMap(key, boxedByteValue), obj.getBoxedByteValueMap());
    Assert.assertEquals(Collections.singletonMap(key, boxedShortValue), obj.getBoxedShortValueMap());
    Assert.assertEquals(Collections.singletonMap(key, boxedIntValue), obj.getBoxedIntValueMap());
    Assert.assertEquals(Collections.singletonMap(key, boxedLongValue), obj.getBoxedLongValueMap());
    Assert.assertEquals(Collections.singletonMap(key, boxedFloatValue), obj.getBoxedFloatValueMap());
    Assert.assertEquals(Collections.singletonMap(key, boxedDoubleValue), obj.getBoxedDoubleValueMap());
    Assert.assertEquals(Collections.singletonMap(key, boxedCharValue), obj.getBoxedCharValueMap());
    Assert.assertEquals(Collections.singletonMap(key, jsonObjectDataObject), obj.getJsonObjectDataObjectValueMap());
    Assert.assertEquals(Collections.singletonMap(key, stringDataObjectValue), obj.getStringDataObjectValueMap());
    Assert.assertEquals(Collections.singletonMap(key, bufferValue), obj.getBufferValueMap());
    Assert.assertEquals(Collections.singletonMap(key, jsonObjectValue), obj.getJsonObjectValueMap());
    Assert.assertEquals(Collections.singletonMap(key, jsonArrayValue), obj.getJsonArrayValueMap());
    Assert.assertEquals(Collections.singletonMap(key, enumValue), obj.getEnumValueMap());
    Assert.assertEquals(Collections.singletonMap(key, methodMappedValue), obj.getMethodMappedValueMap());
    Assert.assertEquals(Collections.singletonMap(key, durationValue), obj.getDurationValueMap());
    Assert.assertEquals(map, obj.getObjectValueMap());
    Assert.assertEquals(1, obj.getNoConverterDataObjectValueMap().size());
    Assert.assertNull(obj.getNoConverter2DataObjectValueMap());
    Assert.assertEquals(Collections.singletonMap(key, customEnumValue), obj.getCustomEnumValueMap());
    Assert.assertEquals(Collections.singletonMap(key, autoMappedValue), obj.getAutoMappedValueMap());
    Assert.assertEquals(Collections.singletonMap(key, autoMappedWithVertxGenValue), obj.getAutoMappedWithVertxGenValueMap());
    Assert.assertEquals(Collections.singletonMap(key, stringValue), obj.getKeyedStringValues());
    Assert.assertEquals(Collections.singletonMap(key, boxedBooleanValue), obj.getKeyedBoxedBooleanValues());
    Assert.assertEquals(Collections.singletonMap(key, boxedByteValue), obj.getKeyedBoxedByteValues());
    Assert.assertEquals(Collections.singletonMap(key, boxedShortValue), obj.getKeyedBoxedShortValues());
    Assert.assertEquals(Collections.singletonMap(key, boxedIntValue), obj.getKeyedBoxedIntValues());
    Assert.assertEquals(Collections.singletonMap(key, boxedLongValue), obj.getKeyedBoxedLongValues());
    Assert.assertEquals(Collections.singletonMap(key, boxedFloatValue), obj.getKeyedBoxedFloatValues());
    Assert.assertEquals(Collections.singletonMap(key, boxedDoubleValue), obj.getKeyedBoxedDoubleValues());
    Assert.assertEquals(Collections.singletonMap(key, boxedCharValue), obj.getKeyedBoxedCharValues());
    Assert.assertEquals(Collections.singletonMap(key, jsonObjectDataObject), obj.getKeyedJsonObjectDataObjectValues());
    Assert.assertEquals(Collections.singletonMap(key, stringDataObjectValue), obj.getKeyedStringDataObjectValues());
    Assert.assertEquals(Collections.singletonMap(key, bufferValue), obj.getKeyedBufferValues());
    Assert.assertEquals(Collections.singletonMap(key, jsonObjectValue), obj.getKeyedJsonObjectValues());
    Assert.assertEquals(Collections.singletonMap(key, jsonArrayValue), obj.getKeyedJsonArrayValues());
    Assert.assertEquals(Collections.singletonMap(key, enumValue), obj.getKeyedEnumValues());
    Assert.assertEquals(Collections.singletonMap(key, methodMappedValue), obj.getKeyedMethodMappedValues());
    Assert.assertEquals(Collections.singletonMap(key, durationValue), obj.getKeyedDurationValues());
    Assert.assertEquals(map, obj.getObjectValueMap());
    Assert.assertEquals(1, obj.getNoConverterDataObjectValueMap().size());
    Assert.assertNull(obj.getNoConverter2DataObjectValueMap());
    Assert.assertEquals(Collections.singletonMap(key, customEnumValue), obj.getKeyedCustomEnumValues());
    Assert.assertEquals(Collections.singletonMap(key, autoMappedValue), obj.getKeyedAutoMappedValues());
    Assert.assertEquals(Collections.singletonMap(key, autoMappedWithVertxGenValue), obj.getKeyedAutoMappedWithVertxGenValues());

    // Sometimes json can use java collections so test it runs fine in this case
//    json = new JsonObject();
//    json.put("aggregatedDataObject", new JsonObject().put("value", aggregatedDataObject.getValue()).getMap());
//    json.put("aggregatedDataObjects", new JsonArray().add(new JsonObject().put("value", aggregatedDataObject.getValue()).getMap()));
//    json.put("addedAggregatedDataObjects", new JsonArray().add(new JsonObject().put("value", aggregatedDataObject.getValue()).getMap()));
//    obj = new TestDataObject();
//    TestDataObjectConverter.fromJson(json, obj);
//    assertEquals(aggregatedDataObject, obj.getAggregatedDataObject());
//    assertEquals(Collections.singletonList(aggregatedDataObject), obj.getAggregatedDataObjects());
//    assertEquals(Collections.singletonList(aggregatedDataObject), obj.getAddedAggregatedDataObjects());
  }

  @Test
  public void testEmptyJsonToDataObject() {

    JsonObject json = new JsonObject();

    TestDataObject obj = new TestDataObject();
    TestDataObjectConverter.fromJson(json, obj);

    Assert.assertEquals(null, obj.getStringValue());
    Assert.assertEquals(false, obj.isPrimitiveBooleanValue());
    Assert.assertEquals(0, obj.getPrimitiveByteValue());
    Assert.assertEquals(0, obj.getPrimitiveShortValue());
    Assert.assertEquals(0, obj.getPrimitiveIntValue());
    Assert.assertEquals(0l, obj.getPrimitiveLongValue());
    Assert.assertEquals(0f, obj.getPrimitiveFloatValue(), 0);
    Assert.assertEquals(0d, obj.getPrimitiveDoubleValue(), 0);
    Assert.assertEquals((char)0, obj.getPrimitiveCharValue());
    Assert.assertEquals(null, obj.isBoxedBooleanValue());
    Assert.assertEquals(null, obj.getBoxedByteValue());
    Assert.assertEquals(null, obj.getBoxedShortValue());
    Assert.assertEquals(null, obj.getBoxedIntValue());
    Assert.assertEquals(null, obj.getBoxedLongValue());
    Assert.assertEquals(null, obj.getBoxedFloatValue());
    Assert.assertEquals(null, obj.getBoxedDoubleValue());
    Assert.assertEquals(null, obj.getBoxedCharValue());
    assertEquals(null, obj.getJsonObjectDataObjectValue());
    assertEquals(null, obj.getStringDataObjectValue());
    Assert.assertEquals(null, obj.getBufferValue());
    Assert.assertEquals(null, obj.getJsonObjectValue());
    Assert.assertEquals(null, obj.getJsonArrayValue());
    Assert.assertEquals(null, obj.getMethodMappedValue());
    Assert.assertEquals(null, obj.getDurationValue());
    Assert.assertEquals(null, obj.getObjectValue());
    Assert.assertEquals(null, obj.getNoConverterDataObjectValue());
    Assert.assertEquals(null, obj.getNoConverter2DataObjectValue());
    Assert.assertEquals(null, obj.getStringValueList());
    Assert.assertEquals(null, obj.getCustomEnumValue());
    Assert.assertEquals(null, obj.getBoxedBooleanValueList());
    Assert.assertEquals(null, obj.getBoxedByteValueList());
    Assert.assertEquals(null, obj.getBoxedShortValueList());
    Assert.assertEquals(null, obj.getBoxedIntValueList());
    Assert.assertEquals(null, obj.getBoxedLongValueList());
    Assert.assertEquals(null, obj.getBoxedFloatValueList());
    Assert.assertEquals(null, obj.getBoxedDoubleValueList());
    Assert.assertEquals(null, obj.getBoxedCharValueList());
    Assert.assertEquals(null, obj.getJsonObjectDataObjectValueList());
    Assert.assertEquals(null, obj.getStringDataObjectValueList());
    Assert.assertEquals(null, obj.getBufferValueList());
    Assert.assertEquals(null, obj.getJsonObjectValueList());
    Assert.assertEquals(null, obj.getJsonArrayValueList());
    Assert.assertEquals(null, obj.getEnumValueList());
    Assert.assertEquals(null, obj.getMethodMappedValueList());
    Assert.assertEquals(null, obj.getDurationValueList());
    Assert.assertEquals(null, obj.getObjectValueList());
    Assert.assertEquals(null, obj.getNoConverterDataObjectValueList());
    Assert.assertEquals(null, obj.getNoConverter2DataObjectValueList());
    Assert.assertEquals(null, obj.getCustomEnumValueList());
    Assert.assertEquals(null, obj.getStringValueSet());
    Assert.assertEquals(null, obj.getBoxedBooleanValueSet());
    Assert.assertEquals(null, obj.getBoxedByteValueSet());
    Assert.assertEquals(null, obj.getBoxedShortValueSet());
    Assert.assertEquals(null, obj.getBoxedIntValueSet());
    Assert.assertEquals(null, obj.getBoxedLongValueSet());
    Assert.assertEquals(null, obj.getBoxedFloatValueSet());
    Assert.assertEquals(null, obj.getBoxedDoubleValueSet());
    Assert.assertEquals(null, obj.getBoxedCharValueSet());
    Assert.assertEquals(null, obj.getJsonObjectDataObjectValueSet());
    Assert.assertEquals(null, obj.getStringDataObjectValueSet());
    Assert.assertEquals(null, obj.getBufferValueSet());
    Assert.assertEquals(null, obj.getJsonObjectValueSet());
    Assert.assertEquals(null, obj.getJsonArrayValueSet());
    Assert.assertEquals(null, obj.getEnumValueSet());
    Assert.assertEquals(null, obj.getMethodMappedValueSet());
    Assert.assertEquals(null, obj.getDurationValueSet());
    Assert.assertEquals(null, obj.getObjectValueSet());
    Assert.assertEquals(null, obj.getNoConverterDataObjectValueSet());
    Assert.assertEquals(null, obj.getNoConverter2DataObjectValueSet());
    Assert.assertEquals(null, obj.getCustomEnumValueSet());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedStringValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedBoxedBooleanValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedBoxedByteValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedBoxedShortValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedBoxedIntValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedBoxedLongValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedBoxedFloatValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedBoxedDoubleValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedBoxedCharValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedJsonObjectDataObjectValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedStringDataObjectValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedBufferValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedJsonObjectValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedJsonArrayValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedEnumValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedMethodMappedValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedDurationValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedObjectValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedNoConverterDataObjectValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedNoConverter2DataObjectValues());
    Assert.assertEquals(Collections.emptyList(), obj.getAddedCustomEnumValues());
    Assert.assertEquals(null, obj.getStringValueMap());
    Assert.assertEquals(null, obj.getBoxedBooleanValueMap());
    Assert.assertEquals(null, obj.getBoxedByteValueMap());
    Assert.assertEquals(null, obj.getBoxedShortValueMap());
    Assert.assertEquals(null, obj.getBoxedIntValueMap());
    Assert.assertEquals(null, obj.getBoxedLongValueMap());
    Assert.assertEquals(null, obj.getBoxedFloatValueMap());
    Assert.assertEquals(null, obj.getBoxedDoubleValueMap());
    Assert.assertEquals(null, obj.getBoxedCharValueMap());
    Assert.assertEquals(null, obj.getJsonObjectDataObjectValueMap());
    Assert.assertEquals(null, obj.getStringDataObjectValueMap());
    Assert.assertEquals(null, obj.getBufferValueMap());
    Assert.assertEquals(null, obj.getJsonObjectValueMap());
    Assert.assertEquals(null, obj.getJsonArrayValueMap());
    Assert.assertEquals(null, obj.getEnumValueMap());
    Assert.assertEquals(null, obj.getMethodMappedValueMap());
    Assert.assertEquals(null, obj.getDurationValueMap());
    Assert.assertEquals(null, obj.getObjectValueMap());
    Assert.assertEquals(null, obj.getNoConverterDataObjectValueMap());
    Assert.assertEquals(null, obj.getNoConverter2DataObjectValueMap());
    Assert.assertEquals(null, obj.getCustomEnumValueMap());
  }

  @Test
  public void testDataObjectToJson() throws Exception {
    String key = TestUtils.randomAlphaString(10);
    String stringValue = TestUtils.randomAlphaString(20);
    boolean booleanValue = TestUtils.randomBoolean();
    byte byteValue = TestUtils.randomByte();
    short shortValue = TestUtils.randomShort();
    int intValue = TestUtils.randomInt();
    long longValue = TestUtils.randomLong();
    float floatValue = TestUtils.randomFloat();
    double doubleValue = TestUtils.randomDouble();
    char charValue = TestUtils.randomChar();
    Boolean boxedBooleanValue = TestUtils.randomBoolean();
    Byte boxedByteValue = TestUtils.randomByte();
    Short boxedShortValue = TestUtils.randomShort();
    Integer boxedIntValue = TestUtils.randomInt();
    Long boxedLongValue = TestUtils.randomLong();
    Float boxedFloatValue = TestUtils.randomFloat();
    Double boxedDoubleValue = TestUtils.randomDouble();
    Character boxedCharValue = TestUtils.randomChar();
    NestedJsonObjectDataObject jsonObjectDataObjectValue = new NestedJsonObjectDataObject().setValue(TestUtils.randomAlphaString(20));
    NestedStringDataObject stringDataObjectValue = new NestedStringDataObject().setValue(TestUtils.randomAlphaString(20));
    Buffer bufferValue = TestUtils.randomBuffer(20);
    JsonObject jsonObjectValue = new JsonObject().put("wibble", TestUtils.randomAlphaString(20));
    JsonArray jsonArrayValue = new JsonArray().add(TestUtils.randomAlphaString(20));
    TimeUnit enumValue = TimeUnit.values()[TestUtils.randomPositiveInt() % TimeUnit.values().length];
    ZonedDateTime methodMappedValue = ZonedDateTime.now();
    Duration durationValue = Duration.ofSeconds(methodMappedValue.toEpochSecond());
    Object objectValue = stringValue;
    TestCustomEnum customEnumValue = TestCustomEnum.DEV;
    AutoMapped autoMappedValue = AutoMapped.of("vertx.io", 80);
    AutoMappedWithVertxGen autoMappedWithVertxGenValue = AutoMappedWithVertxGen.of("vertx.io", 80);
    UUID uuidValue = UUID.randomUUID();

    Map<String, Object> map = new HashMap<>();
    map.put(TestUtils.randomAlphaString(10), TestUtils.randomAlphaString(20));
    map.put(TestUtils.randomAlphaString(10), TestUtils.randomBoolean());
    map.put(TestUtils.randomAlphaString(10), TestUtils.randomInt());
    List<Object> list = new ArrayList<>();
    list.add(TestUtils.randomAlphaString(20));
    list.add(TestUtils.randomBoolean());
    list.add(TestUtils.randomInt());

    TestDataObject obj = new TestDataObject();
    obj.setStringValue(stringValue);
    obj.setPrimitiveBooleanValue(booleanValue);
    obj.setPrimitiveByteValue(byteValue);
    obj.setPrimitiveShortValue(shortValue);
    obj.setPrimitiveIntValue(intValue);
    obj.setPrimitiveLongValue(longValue);
    obj.setPrimitiveFloatValue(floatValue);
    obj.setPrimitiveDoubleValue(doubleValue);
    obj.setPrimitiveCharValue(charValue);
    obj.setBoxedBooleanValue(boxedBooleanValue);
    obj.setBoxedByteValue(boxedByteValue);
    obj.setBoxedShortValue(boxedShortValue);
    obj.setBoxedIntValue(boxedIntValue);
    obj.setBoxedLongValue(boxedLongValue);
    obj.setBoxedFloatValue(boxedFloatValue);
    obj.setBoxedDoubleValue(boxedDoubleValue);
    obj.setBoxedCharValue(boxedCharValue);
    obj.setObjectValue(objectValue);
    obj.setJsonObjectDataObjectValue(jsonObjectDataObjectValue);
    obj.setStringDataObjectValue(stringDataObjectValue);
    obj.setBufferValue(bufferValue);
    obj.setJsonObjectValue(jsonObjectValue);
    obj.setJsonArrayValue(jsonArrayValue);
    obj.setEnumValue(enumValue);
    obj.setMethodMappedValue(methodMappedValue);
    obj.setDurationValue(durationValue);
    obj.setObjectValue(objectValue);
    obj.setNoConverterDataObjectValue(new NoConverterDataObject());
    obj.setNoConverter2DataObjectValue(new NoConverter2DataObject());
    obj.setCustomEnumValue(customEnumValue);
    obj.setAutoMappedValue(autoMappedValue);
    obj.setAutoMappedWithVertxGenValue(autoMappedWithVertxGenValue);
    obj.setUuidValue(uuidValue);
    obj.setStringValueList(Collections.singletonList(stringValue));
    obj.setBoxedBooleanValueList(Collections.singletonList(boxedBooleanValue));
    obj.setBoxedByteValueList(Collections.singletonList(boxedByteValue));
    obj.setBoxedShortValueList(Collections.singletonList(boxedShortValue));
    obj.setBoxedIntValueList(Collections.singletonList(boxedIntValue));
    obj.setBoxedLongValueList(Collections.singletonList(boxedLongValue));
    obj.setBoxedFloatValueList(Collections.singletonList(boxedFloatValue));
    obj.setBoxedDoubleValueList(Collections.singletonList(boxedDoubleValue));
    obj.setBoxedCharValueList(Collections.singletonList(boxedCharValue));
    obj.setJsonObjectDataObjectValueList(Collections.singletonList(jsonObjectDataObjectValue));
    obj.setStringDataObjectValueList(Collections.singletonList(stringDataObjectValue));
    obj.setBufferValueList(Collections.singletonList(bufferValue));
    obj.setJsonObjectValueList(Collections.singletonList(jsonObjectValue));
    obj.setJsonArrayValueList(Collections.singletonList(jsonArrayValue));
    obj.setEnumValueList(Collections.singletonList(enumValue));
    obj.setMethodMappedValueList(Collections.singletonList(methodMappedValue));
    obj.setDurationValueList(Collections.singletonList(durationValue));
    obj.setObjectValueList(list);
    obj.setNoConverterDataObjectValueList(Collections.singletonList(new NoConverterDataObject()));
    obj.setNoConverter2DataObjectValueList(Collections.singletonList(new NoConverter2DataObject()));
    obj.setCustomEnumValueList(Collections.singletonList(customEnumValue));
    obj.setAutoMappedValueList(Collections.singletonList(autoMappedValue));
    obj.setAutoMappedWithVertxGenValueList(Collections.singletonList(autoMappedWithVertxGenValue));
    obj.setStringValueMap(Collections.singletonMap(key, stringValue));
    obj.setStringValueSet(Collections.singleton(stringValue));
    obj.setBoxedBooleanValueSet(Collections.singleton(boxedBooleanValue));
    obj.setBoxedByteValueSet(Collections.singleton(boxedByteValue));
    obj.setBoxedShortValueSet(Collections.singleton(boxedShortValue));
    obj.setBoxedIntValueSet(Collections.singleton(boxedIntValue));
    obj.setBoxedLongValueSet(Collections.singleton(boxedLongValue));
    obj.setBoxedFloatValueSet(Collections.singleton(boxedFloatValue));
    obj.setBoxedDoubleValueSet(Collections.singleton(boxedDoubleValue));
    obj.setBoxedCharValueSet(Collections.singleton(boxedCharValue));
    obj.setJsonObjectDataObjectValueSet(Collections.singleton(jsonObjectDataObjectValue));
    obj.setStringDataObjectValueSet(Collections.singleton(stringDataObjectValue));
    obj.setBufferValueSet(Collections.singleton(bufferValue));
    obj.setJsonObjectValueSet(Collections.singleton(jsonObjectValue));
    obj.setJsonArrayValueSet(Collections.singleton(jsonArrayValue));
    obj.setEnumValueSet(Collections.singleton(enumValue));
    obj.setMethodMappedValueSet(Collections.singleton(methodMappedValue));
    obj.setDurationValueSet(Collections.singleton(durationValue));
    obj.setObjectValueSet(new LinkedHashSet<>(list));
    obj.setNoConverterDataObjectValueSet(Collections.singleton(new NoConverterDataObject()));
    obj.setNoConverter2DataObjectValueSet(Collections.singleton(new NoConverter2DataObject()));
    obj.setCustomEnumValueSet(Collections.singleton(customEnumValue));
    obj.setAutoMappedValueSet(Collections.singleton(autoMappedValue));
    obj.setAutoMappedWithVertxGenValueSet(Collections.singleton(autoMappedWithVertxGenValue));
    obj.setBoxedBooleanValueMap(Collections.singletonMap(key, boxedBooleanValue));
    obj.setBoxedByteValueMap(Collections.singletonMap(key, boxedByteValue));
    obj.setBoxedShortValueMap(Collections.singletonMap(key, boxedShortValue));
    obj.setBoxedIntValueMap(Collections.singletonMap(key, boxedIntValue));
    obj.setBoxedLongValueMap(Collections.singletonMap(key, boxedLongValue));
    obj.setBoxedFloatValueMap(Collections.singletonMap(key, boxedFloatValue));
    obj.setBoxedDoubleValueMap(Collections.singletonMap(key, boxedDoubleValue));
    obj.setBoxedCharValueMap(Collections.singletonMap(key, boxedCharValue));
    obj.setJsonObjectDataObjectValueMap(Collections.singletonMap(key, jsonObjectDataObjectValue));
    obj.setStringDataObjectValueMap(Collections.singletonMap(key, stringDataObjectValue));
    obj.setBufferValueMap(Collections.singletonMap(key, bufferValue));
    obj.setJsonObjectValueMap(Collections.singletonMap(key, jsonObjectValue));
    obj.setJsonArrayValueMap(Collections.singletonMap(key, jsonArrayValue));
    obj.setEnumValueMap(Collections.singletonMap(key, enumValue));
    obj.setDurationValueMap(Collections.singletonMap(key, durationValue));
    obj.setObjectValueMap(map);
    obj.setNoConverterDataObjectValueMap(Collections.singletonMap(key, new NoConverterDataObject()));
    obj.setNoConverter2DataObjectValueMap(Collections.singletonMap(key, new NoConverter2DataObject()));
    obj.setCustomEnumValueMap(Collections.singletonMap(key, customEnumValue));
    obj.setAutoMappedValueMap(Collections.singletonMap(key, autoMappedValue));
    obj.setAutoMappedWithVertxGenValueMap(Collections.singletonMap(key, autoMappedWithVertxGenValue));
    obj.addKeyedStringValue(key, stringValue);
    obj.addKeyedBoxedBooleanValue(key, boxedBooleanValue);
    obj.addKeyedBoxedByteValue(key, boxedByteValue);
    obj.addKeyedBoxedShortValue(key, boxedShortValue);
    obj.addKeyedBoxedIntValue(key, boxedIntValue);
    obj.addKeyedBoxedLongValue(key, boxedLongValue);
    obj.addKeyedBoxedFloatValue(key, boxedFloatValue);
    obj.addKeyedBoxedDoubleValue(key, boxedDoubleValue);
    obj.addKeyedBoxedCharValue(key, boxedCharValue);
    obj.addKeyedJsonObjectDataObjectValue(key, jsonObjectDataObjectValue);
    obj.addKeyedStringDataObjectValue(key, stringDataObjectValue);
    obj.addKeyedBufferValue(key, bufferValue);
    obj.addKeyedJsonObjectValue(key, jsonObjectValue);
    obj.addKeyedJsonArrayValue(key, jsonArrayValue);
    obj.addKeyedEnumValue(key, enumValue);
    obj.addKeyedMethodMappedValue(key, methodMappedValue);
    obj.addKeyedDurationValue(key, durationValue);
    map.forEach(obj::addKeyedObjectValue);
    obj.addKeyedNoConverterDataObjectValue(key, new NoConverterDataObject());
    obj.addKeyedNoConverter2DataObjectValue(key, new NoConverter2DataObject());
    obj.addKeyedCustomEnumValue(key, customEnumValue);
    obj.addKeyedAutoMappedValue(key, autoMappedValue);
    obj.addKeyedAutoMappedWithVertxGenValue(key, autoMappedWithVertxGenValue);

    Map<String, Object> json = new HashMap<>();
    TestDataObjectConverter.toJson(obj, json);

    assertEquals(stringValue, json.get("stringValue"));
    assertEquals(booleanValue, json.get("primitiveBooleanValue"));
    assertEquals(byteValue, (byte)json.get("primitiveByteValue"));
    assertEquals(shortValue, (short)json.get("primitiveShortValue"));
    assertEquals(intValue, (int)json.get("primitiveIntValue"));
    assertEquals(longValue, (long)json.get("primitiveLongValue"));
    assertEquals(floatValue, (float)json.get("primitiveFloatValue"), 0.001);
    assertEquals(doubleValue, (double)json.get("primitiveDoubleValue"), 0.001);
    assertEquals(Character.toString(charValue), json.get("primitiveCharValue"));
    assertEquals(boxedBooleanValue, json.get("boxedBooleanValue"));
    assertEquals((byte)boxedByteValue, (byte)json.get("boxedByteValue"));
    assertEquals((short)boxedShortValue, (short)json.get("boxedShortValue"));
    assertEquals(boxedIntValue, json.get("boxedIntValue"));
    assertEquals(boxedLongValue, json.get("boxedLongValue"));
    assertEquals(boxedFloatValue, (float)json.get("boxedFloatValue"), 0.001);
    assertEquals(boxedDoubleValue, (double) json.get("boxedDoubleValue"), 0.001);
    assertEquals(Character.toString(boxedCharValue), json.get("boxedCharValue"));
    assertEquals(jsonObjectDataObjectValue.toJson(), json.get("jsonObjectDataObjectValue"));
    assertEquals(stringDataObjectValue.toJson(), json.get("stringDataObjectValue"));
    assertEquals(bufferValue, Buffer.buffer(BASE64_DECODER.decode((String)json.get("bufferValue"))));
    assertEquals(jsonObjectValue, json.get("jsonObjectValue"));
    assertEquals(jsonArrayValue, json.get("jsonArrayValue"));
    assertEquals(enumValue.name(), json.get("enumValue"));
    assertEquals(methodMappedValue.toString(), json.get("methodMappedValue"));
    assertEquals(durationValue.toMillis(), json.get("durationValue"));
    assertEquals(uuidValue.toString(), json.get("uuidValue"));
    assertEquals(objectValue, json.get("objectValue"));
    assertNull(json.get("noConverterDataObjectValue"));
    assertEquals(new JsonObject(), json.get("noConverter2DataObjectValue"));
    assertEquals(customEnumValue.getShortName(), json.get("customEnumValue"));
    assertEquals(autoMappedValue.toJson(), json.get("autoMappedValue"));
    assertEquals(autoMappedWithVertxGenValue.toJson(), json.get("autoMappedWithVertxGenValue"));
    assertEquals(new JsonArray().add(stringValue), json.get("stringValueList"));
    assertEquals(new JsonArray().add(boxedBooleanValue), json.get("boxedBooleanValueList"));
    assertEquals(new JsonArray().add(boxedByteValue), json.get("boxedByteValueList"));
    assertEquals(new JsonArray().add(boxedShortValue), json.get("boxedShortValueList"));
    assertEquals(new JsonArray().add(boxedIntValue), json.get("boxedIntValueList"));
    assertEquals(new JsonArray().add(boxedLongValue), json.get("boxedLongValueList"));
    assertEquals(1, ((JsonArray)json.get("boxedFloatValueList")).size());
    assertEquals(boxedFloatValue, (float)((JsonArray)json.get("boxedFloatValueList")).getValue(0), 0.001);
    assertEquals(1, ((JsonArray)json.get("boxedDoubleValueList")).size());
    assertEquals(boxedDoubleValue, (double)((JsonArray)json.get("boxedDoubleValueList")).getValue(0), 0.001);
    assertEquals(new JsonArray().add(Character.toString(boxedCharValue)), json.get("boxedCharValueList"));
    assertEquals(new JsonArray().add(jsonObjectDataObjectValue.toJson()), json.get("jsonObjectDataObjectValueList"));
    assertEquals(new JsonArray().add(stringDataObjectValue.toJson()), json.get("stringDataObjectValueList"));
    assertEquals(BASE64_ENCODER.encodeToString(bufferValue.getBytes()), ((JsonArray)json.get("bufferValueList")).getValue(0));
    assertEquals(new JsonArray().add(jsonObjectValue), json.get("jsonObjectValueList"));
    assertEquals(new JsonArray().add(jsonArrayValue), json.get("jsonArrayValueList"));
    assertEquals(new JsonArray().add(enumValue.name()), json.get("enumValueList"));
    assertEquals(new JsonArray().add(methodMappedValue.toString()), json.get("methodMappedValueList"));
    assertEquals(new JsonArray().add(durationValue.toMillis()), json.get("durationValueList"));
    assertEquals(new JsonArray().add(list.get(0)).add(list.get(1)).add(list.get(2)), json.get("objectValueList"));
    assertNull(json.get("noConverterDataObjectValueList"));
    assertEquals(new JsonArray().add(new JsonObject()), json.get("noConverter2DataObjectValueList"));
    assertEquals(new JsonArray().add(customEnumValue.getShortName()), json.get("customEnumValueList"));
    assertEquals(new JsonArray().add(autoMappedValue.toJson()), json.get("autoMappedValueList"));
    assertEquals(new JsonArray().add(autoMappedWithVertxGenValue.toJson()), json.get("autoMappedWithVertxGenValueList"));
    assertEquals(new JsonArray().add(stringValue), json.get("stringValueSet"));
    assertEquals(new JsonArray().add(boxedBooleanValue), json.get("boxedBooleanValueSet"));
    assertEquals(new JsonArray().add(boxedByteValue), json.get("boxedByteValueSet"));
    assertEquals(new JsonArray().add(boxedShortValue), json.get("boxedShortValueSet"));
    assertEquals(new JsonArray().add(boxedIntValue), json.get("boxedIntValueSet"));
    assertEquals(new JsonArray().add(boxedLongValue), json.get("boxedLongValueSet"));
    assertEquals(1, ((JsonArray)json.get("boxedFloatValueSet")).size());
    assertEquals(boxedFloatValue, (float)((JsonArray)json.get("boxedFloatValueSet")).getValue(0), 0.001);
    assertEquals(1, ((JsonArray)json.get("boxedDoubleValueSet")).size());
    assertEquals(boxedDoubleValue, (double)((JsonArray)json.get("boxedDoubleValueSet")).getValue(0), 0.001);
    assertEquals(new JsonArray().add(Character.toString(boxedCharValue)), json.get("boxedCharValueSet"));
    assertEquals(new JsonArray().add(jsonObjectDataObjectValue.toJson()), json.get("jsonObjectDataObjectValueSet"));
    assertEquals(new JsonArray().add(stringDataObjectValue.toJson()), json.get("stringDataObjectValueSet"));
    assertEquals(BASE64_ENCODER.encodeToString(bufferValue.getBytes()), ((JsonArray)json.get("bufferValueSet")).getValue(0));
    assertEquals(new JsonArray().add(jsonObjectValue), json.get("jsonObjectValueSet"));
    assertEquals(new JsonArray().add(jsonArrayValue), json.get("jsonArrayValueSet"));
    assertEquals(new JsonArray().add(enumValue.name()), json.get("enumValueSet"));
    assertEquals(new JsonArray().add(methodMappedValue.toString()), json.get("methodMappedValueSet"));
    assertEquals(new JsonArray().add(durationValue.toMillis()), json.get("durationValueSet"));
    assertEquals(new JsonArray().add(list.get(0)).add(list.get(1)).add(list.get(2)), json.get("objectValueSet"));
    assertNull(json.get("noConverterDataObjectValueSet"));
    assertEquals(new JsonArray().add(new JsonObject()), json.get("noConverter2DataObjectValueSet"));
    assertEquals(new JsonArray().add(customEnumValue.getShortName()), json.get("customEnumValueSet"));
    assertEquals(new JsonArray().add(autoMappedValue.toJson()), json.get("autoMappedValueSet"));
    assertEquals(new JsonArray().add(autoMappedWithVertxGenValue.toJson()), json.get("autoMappedWithVertxGenValueSet"));
    assertEquals(new JsonObject().put(key, stringValue), json.get("stringValueMap"));
    assertEquals(new JsonObject().put(key, boxedBooleanValue), json.get("boxedBooleanValueMap"));
    assertEquals(new JsonObject().put(key, boxedByteValue), json.get("boxedByteValueMap"));
    assertEquals(new JsonObject().put(key, boxedShortValue), json.get("boxedShortValueMap"));
    assertEquals(new JsonObject().put(key, boxedIntValue), json.get("boxedIntValueMap"));
    assertEquals(new JsonObject().put(key, boxedLongValue), json.get("boxedLongValueMap"));
    assertEquals(1, ((JsonObject)json.get("boxedFloatValueMap")).size());
    assertEquals(boxedFloatValue, (float)((JsonObject)json.get("boxedFloatValueMap")).getValue(key), 0.001);
    assertEquals(1, ((JsonObject)json.get("boxedDoubleValueMap")).size());
    assertEquals(boxedDoubleValue, (double)((JsonObject)json.get("boxedDoubleValueMap")).getValue(key), 0.001);
    assertEquals(new JsonObject().put(key, Character.toString(boxedCharValue)), json.get("boxedCharValueMap"));
    assertEquals(new JsonObject().put(key, jsonObjectDataObjectValue.toJson()), json.get("jsonObjectDataObjectValueMap"));
    assertEquals(new JsonObject().put(key, stringDataObjectValue.toJson()), json.get("stringDataObjectValueMap"));
    assertEquals(BASE64_ENCODER.encodeToString(bufferValue.getBytes()), ((JsonObject)json.get("bufferValueMap")).getValue(key));
    assertEquals(new JsonObject().put(key, jsonObjectValue), json.get("jsonObjectValueMap"));
    assertEquals(new JsonObject().put(key, jsonArrayValue), json.get("jsonArrayValueMap"));
    assertEquals(new JsonObject().put(key, enumValue.name()), json.get("enumValueMap"));
    assertEquals(new JsonObject().put(key, durationValue.toMillis()), json.get("durationValueMap"));
    assertEquals(toJson(map), json.get("objectValueMap"));
    assertNull(json.get("noConverterDataObjectValueMap"));
    assertEquals(new JsonObject().put(key, new JsonObject()), json.get("noConverter2DataObjectValueMap"));
    assertEquals(new JsonObject().put(key, customEnumValue.getShortName()), json.get("customEnumValueMap"));
    assertEquals(new JsonObject().put(key, autoMappedValue.toJson()), json.get("autoMappedValueMap"));
    assertEquals(new JsonObject().put(key, autoMappedWithVertxGenValue.toJson()), json.get("autoMappedWithVertxGenValueMap"));
    assertEquals(new JsonObject().put(key, stringValue), json.get("keyedStringValues"));
    assertEquals(new JsonObject().put(key, boxedBooleanValue), json.get("keyedBoxedBooleanValues"));
    assertEquals(new JsonObject().put(key, boxedByteValue), json.get("keyedBoxedByteValues"));
    assertEquals(new JsonObject().put(key, boxedShortValue), json.get("keyedBoxedShortValues"));
    assertEquals(new JsonObject().put(key, boxedIntValue), json.get("keyedBoxedIntValues"));
    assertEquals(new JsonObject().put(key, boxedLongValue), json.get("keyedBoxedLongValues"));
    assertEquals(1, ((JsonObject)json.get("keyedBoxedFloatValues")).size());
    assertEquals(boxedFloatValue, (float)((JsonObject)json.get("keyedBoxedFloatValues")).getValue(key), 0.001);
    assertEquals(1, ((JsonObject)json.get("keyedBoxedDoubleValues")).size());
    assertEquals(boxedDoubleValue, (double)((JsonObject)json.get("keyedBoxedDoubleValues")).getValue(key), 0.001);
    assertEquals(new JsonObject().put(key, Character.toString(boxedCharValue)), json.get("keyedBoxedCharValues"));
    assertEquals(new JsonObject().put(key, jsonObjectDataObjectValue.toJson()), json.get("keyedJsonObjectDataObjectValues"));
    assertEquals(new JsonObject().put(key, stringDataObjectValue.toJson()), json.get("keyedStringDataObjectValues"));
    assertEquals(BASE64_ENCODER.encodeToString(bufferValue.getBytes()), ((JsonObject)json.get("keyedBufferValues")).getValue(key));
    assertEquals(new JsonObject().put(key, jsonObjectValue), json.get("keyedJsonObjectValues"));
    assertEquals(new JsonObject().put(key, jsonArrayValue), json.get("keyedJsonArrayValues"));
    assertEquals(new JsonObject().put(key, enumValue.name()), json.get("keyedEnumValues"));
    assertEquals(new JsonObject().put(key, durationValue.toMillis()), json.get("keyedDurationValues"));
    assertEquals(toJson(map), json.get("keyedObjectValues"));
    assertNull(json.get("keyedNoConverterDataObjectValues"));
    assertEquals(new JsonObject().put(key, new JsonObject()), json.get("keyedNoConverter2DataObjectValues"));
    assertEquals(new JsonObject().put(key, customEnumValue.getShortName()), json.get("keyedCustomEnumValues"));
    assertEquals(new JsonObject().put(key, autoMappedValue.toJson()), json.get("keyedAutoMappedValues"));
    assertEquals(new JsonObject().put(key, autoMappedWithVertxGenValue.toJson()), json.get("keyedAutoMappedWithVertxGenValues"));
  }

  @Test
  public void testEmptyDataObjectToJson() {

    TestDataObject obj = new TestDataObject();

    Map<String, Object> json = new HashMap<>();
    TestDataObjectConverter.toJson(obj, json);

    assertEquals(null, json.get("stringValue"));
    assertEquals(false, json.get("primitiveBooleanValue"));
    assertEquals(0, (byte)json.get("primitiveByteValue"));
    assertEquals(0, (short)json.get("primitiveShortValue"));
    assertEquals(0, (int)json.get("primitiveIntValue"));
    assertEquals(0L, (long) json.get("primitiveLongValue"));
    assertEquals(0f, (float) json.get("primitiveFloatValue"), 0);
    assertEquals(0d, (double) json.get("primitiveDoubleValue"), 0);
    assertEquals(Character.toString((char)0), json.get("primitiveCharValue"));
    assertEquals(null, json.get("boxedBooleanValue"));
    assertEquals(null, json.get("boxedByteValue"));
    assertEquals(null, json.get("boxedShortValue"));
    assertEquals(null, json.get("boxedIntValue"));
    assertEquals(null, json.get("boxedLongValue"));
    assertEquals(null, json.get("boxedFloatValue"));
    assertEquals(null, json.get("boxedDoubleValue"));
    assertEquals(null, json.get("boxedCharValue"));
    assertEquals(null, json.get("jsonObjectDataObjectValue"));
    assertEquals(null, json.get("stringDataObjectValue"));
    assertEquals(null, json.get("bufferValue"));
    assertEquals(null, json.get("jsonObjectValue"));
    assertEquals(null, json.get("jsonArrayValue"));
    assertEquals(null, json.get("enumValue"));
    assertEquals(null, json.get("methodMappedValue"));
    assertEquals(null, json.get("noConverterDataObjectValue"));
    assertEquals(null, json.get("noConverter2DataObjectValue"));
    assertEquals(null, json.get("customEnumValue"));
    assertEquals(null, json.get("autoMappedValue"));
    assertEquals(null, json.get("autoMappedWithVertxGenValue"));
    assertEquals(null, json.get("stringValueList"));
    assertEquals(null, json.get("boxedBooleanValueList"));
    assertEquals(null, json.get("boxedByteValueList"));
    assertEquals(null, json.get("boxedShortValueList"));
    assertEquals(null, json.get("boxedIntValueList"));
    assertEquals(null, json.get("boxedLongValueList"));
    assertEquals(null, json.get("boxedFloatValueList"));
    assertEquals(null, json.get("boxedDoubleValueList"));
    assertEquals(null, json.get("boxedCharValueList"));
    assertEquals(null, json.get("jsonObjectDataObjectValueList"));
    assertEquals(null, json.get("stringDataObjectValueList"));
    assertEquals(null, json.get("bufferValueList"));
    assertEquals(null, json.get("jsonObjectValueList"));
    assertEquals(null, json.get("jsonArrayValueList"));
    assertEquals(null, json.get("enumValueList"));
    assertEquals(null, json.get("methodMappedValueList"));
    assertEquals(null, json.get("objectValueList"));
    assertEquals(null, json.get("customEnumValueList"));
    assertEquals(null, json.get("autoMappedValueList"));
    assertEquals(null, json.get("autoMappedWithVertxGenValueList"));
    assertEquals(null, json.get("stringValueSet"));
    assertEquals(null, json.get("boxedBooleanValueSet"));
    assertEquals(null, json.get("boxedByteValueSet"));
    assertEquals(null, json.get("boxedShortValueSet"));
    assertEquals(null, json.get("boxedIntValueSet"));
    assertEquals(null, json.get("boxedLongValueSet"));
    assertEquals(null, json.get("boxedFloatValueSet"));
    assertEquals(null, json.get("boxedDoubleValueSet"));
    assertEquals(null, json.get("boxedCharValueSet"));
    assertEquals(null, json.get("jsonObjectDataObjectValueSet"));
    assertEquals(null, json.get("stringDataObjectValueSet"));
    assertEquals(null, json.get("bufferValueSet"));
    assertEquals(null, json.get("jsonObjectValueSet"));
    assertEquals(null, json.get("jsonArrayValueSet"));
    assertEquals(null, json.get("enumValueSet"));
    assertEquals(null, json.get("methodMappedValueSet"));
    assertEquals(null, json.get("objectValueSet"));
    assertEquals(null, json.get("noConverterDataObjectValueSet"));
    assertEquals(null, json.get("noConverter2DataObjectValueSet"));
    assertEquals(null, json.get("customEnumValueSet"));
    assertEquals(null, json.get("autoMappedValueSet"));
    assertEquals(null, json.get("autoMappedWithVertxGenValueSet"));
    assertEquals(new JsonArray(), json.get("addedStringValues"));
    assertEquals(new JsonArray(), json.get("addedBoxedBooleanValues"));
    assertEquals(new JsonArray(), json.get("addedBoxedByteValues"));
    assertEquals(new JsonArray(), json.get("addedBoxedShortValues"));
    assertEquals(new JsonArray(), json.get("addedBoxedIntValues"));
    assertEquals(new JsonArray(), json.get("addedBoxedLongValues"));
    assertEquals(new JsonArray(), json.get("addedBoxedFloatValues"));
    assertEquals(new JsonArray(), json.get("addedBoxedDoubleValues"));
    assertEquals(new JsonArray(), json.get("addedBoxedCharValues"));
    assertEquals(new JsonArray(), json.get("addedStringDataObjectValues"));
    assertEquals(new JsonArray(), json.get("addedBufferValues"));
    assertEquals(new JsonArray(), json.get("addedJsonObjectValues"));
    assertEquals(new JsonArray(), json.get("addedJsonArrayValues"));
    assertEquals(new JsonArray(), json.get("addedEnumValues"));
    assertEquals(new JsonArray(), json.get("addedMethodMappedValues"));
    assertEquals(new JsonArray(), json.get("addedObjectValues"));
    assertEquals(null, json.get("addedNoConverterDataObjectValues"));
    assertEquals(new JsonArray(), json.get("addedNoConverter2DataObjectValues"));
    assertEquals(new JsonArray(), json.get("addedCustomEnumValues"));
    assertEquals(new JsonArray(), json.get("addedAutoMappedValues"));
    assertEquals(new JsonArray(), json.get("addedAutoMappedWithVertxGenValues"));
    assertEquals(null, json.get("stringValueMap"));
    assertEquals(null, json.get("boxedBooleanValueMap"));
    assertEquals(null, json.get("boxedByteValueMap"));
    assertEquals(null, json.get("boxedShortValueMap"));
    assertEquals(null, json.get("boxedIntValueMap"));
    assertEquals(null, json.get("boxedLongValueMap"));
    assertEquals(null, json.get("boxedFloatValueMap"));
    assertEquals(null, json.get("boxedDoubleValueMap"));
    assertEquals(null, json.get("boxedCharValueMap"));
    assertEquals(null, json.get("stringDataObjectValueMap"));
    assertEquals(null, json.get("bufferValueMap"));
    assertEquals(null, json.get("jsonObjectValueMap"));
    assertEquals(null, json.get("jsonArrayValueMap"));
    assertEquals(null, json.get("enumValueMap"));
    assertEquals(null, json.get("methodMappedValueMap"));
    assertEquals(null, json.get("objectValueMap"));
    assertEquals(null, json.get("noConverterDataObjectValueMap"));
    assertEquals(null, json.get("noConverter2DataObjectValueMap"));
    assertEquals(null, json.get("customEnumValueMap"));
    assertEquals(null, json.get("autoMappedValueMap"));
    assertEquals(null, json.get("autoMappedWithVertxGenValueMap"));
  }

  @Test
  public void testInherit() {
    ChildInheritingDataObject obj = new ChildInheritingDataObject();
    JsonObject expectedJson = new JsonObject();
    expectedJson.put("childProperty", "childProperty_value");
    expectedJson.put("parentProperty", "parentProperty_value");
    ChildInheritingDataObjectConverter.fromJson(expectedJson, obj);
    assertEquals("childProperty_value", obj.getChildProperty());
    assertEquals("parentProperty_value", obj.getParentProperty());
    JsonObject json = new JsonObject();
    ChildInheritingDataObjectConverter.toJson(obj, json);
    assertEquals(expectedJson, json);
  }

  @Test
  public void testNotInherit() {
    ChildNotInheritingDataObject obj = new ChildNotInheritingDataObject();
    JsonObject expectedJson = new JsonObject();
    expectedJson.put("childProperty", "childProperty_value");
    expectedJson.put("parentProperty", "parentProperty_value");
    ChildNotInheritingDataObjectConverter.fromJson(expectedJson, obj);
    assertEquals("childProperty_value", obj.getChildProperty());
    assertEquals(null, obj.getParentProperty());
    JsonObject json = new JsonObject();
    ChildNotInheritingDataObjectConverter.toJson(obj, json);
    expectedJson.remove("parentProperty");
    assertEquals(expectedJson, json);
  }

  private String toBase64(Buffer buffer) {
    return BASE64_ENCODER.encodeToString(buffer.getBytes());
  }

  @Test
  public void testPreferSetterToAdder() {
    SetterAdderDataObject obj = new SetterAdderDataObject();
    SetterAdderDataObjectConverter.fromJson(new JsonObject().put("values", new JsonArray().add("first").add("second")), obj);
    Assert.assertEquals(Arrays.asList("first", "second"), obj.getValues());
    Assert.assertEquals(1, obj.sets);
    Assert.assertEquals(0, obj.adds);
  }

  @Test
  public void testSnakeFormatted() {
    SnakeFormattedDataObject obj = new SnakeFormattedDataObject();
    JsonObject expected = new JsonObject()
      .put("foo", "val1")
      .put("foo_bar", "val2")
      .put("foo_bar_juu", "val3");
    SnakeFormattedDataObjectConverter.fromJson(expected
      , obj);
    Assert.assertEquals("val1", obj.getFoo());
    Assert.assertEquals("val2", obj.getFooBar());
    Assert.assertEquals("val3", obj.getFooBarJuu());
    JsonObject test = new JsonObject();
    SnakeFormattedDataObjectConverter.toJson(obj, test);
    Assert.assertEquals(expected, test);
  }

  @Test
  public void testBase64URL() {
    TestDataObjectBase64URL obj = new TestDataObjectBase64URL();
    JsonObject expected = new JsonObject()
      .put("data", "PDw_Pz8-Pg");

    // parse
    TestDataObjectBase64URLConverter.fromJson(expected, obj);
    Assert.assertEquals(Buffer.buffer("<<???>>".getBytes(StandardCharsets.UTF_8)), obj.getData());

    // encode
    JsonObject json = new JsonObject();
    TestDataObjectBase64URLConverter.toJson(obj, json);
    Assert.assertEquals("PDw_Pz8-Pg", json.getValue("data"));
  }

  @Test(expected = IllegalArgumentException.class)
  public void testBase64URLBad() {
    TestDataObjectBase64URL obj = new TestDataObjectBase64URL();
    JsonObject expected = new JsonObject()
      .put("data", "PDw/Pz8+Pg==");

    // parse should fail
    TestDataObjectBase64URLConverter.fromJson(expected, obj);
  }
}
